<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Measurement;
use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getMeasurements($id, $manager) {

        $repo = $manager->getRepository(Measurement::class);
        $measurements = $repo->findBy(['client' => $id]);

        return $measurements;
    }
}
